import { doc, getDoc, serverTimestamp, setDoc } from 'firebase/firestore';
import { db, firebaseEnabled } from '../firebase/firebase';

export const defaultSiteContent = {
  home: {
    heroTitle: 'Tu próxima inversión, comienza con una buena decisión',
    heroSubtitle: 'Te acompaño a tomar decisiones inteligentes que te permitan proteger, construir y multiplicar tu patrimonio con seguridad y visión de futuro',
    heroLabel: 'Estrategia – Experiencia – Resultados',
    heroButton: 'Ir a WhatsApp',
    solutionsKicker: 'SOLUCIONES INTEGRALES',
    solutionsTitle: 'Para tu crecimiento financiero',
    solutionRealEstateTitle: 'Bienes Raíces',
    solutionRealEstateText: 'Encuentra oportunidades inmobiliarias estratégicas que generen valor, estabilidad y crecimiento en el tiempo. Te asesoro en cada paso para que tomes decisiones seguras y rentables.',
    solutionInsuranceTitle: 'Seguros',
    solutionInsuranceText: 'Protege lo que has construido con soluciones diseñadas para resguardar tu patrimonio, tu familia y tu tranquilidad.',
    solutionInvestmentsTitle: 'Inversiones',
    solutionInvestmentsText: 'Diseñamos estrategias personalizadas para hacer crecer tu dinero con visión, control y propósito. Invertir bien no es suerte, es estructura.',
    homeAboutLabel: 'Sobre Mi',
    homeAboutHeadline: 'ASESORA INMOBILIARIA, SEGUROS\nE INVERSIONES',
    homeAboutText: 'Mi propósito es acompañarte a tomar decisiones que te den tranquilidad hoy y construyan tu futuro mañana.\n\nTrabajo con una visión clara: ayudarte a proteger, estructurar y hacer crecer tu patrimonio de forma estratégica, sin improvisaciones y con total confianza.',
    strategicTitle: 'Decisiones que hoy te dan paz, mañana te dan futuro.',
    strategicLabel: 'SOLUCIONES INTEGRALES',
    featuredEyebrow: 'SELECCIÓN ESPECIAL',
    featuredTitle: 'Propiedades destacadas',
    featuredViewAll: 'Ver más propiedades',
  },
  about: {
    heroTitlePrimary: 'ASESORA INMOBILIARIA,',
    heroTitleGold: 'SEGUROS',
    heroTitleSecondary: 'E INVERSIONES',
    heroIntroLead: 'Asesora Estratégica en Bienes Raíces, Seguros e Inversiones',
    heroIntro1: 'Creo que las mejores decisiones financieras no se toman por impulso, sino con estrategia, información y la asesoría correcta.',
    heroIntro2: 'Mi misión es acompañar a familias, profesionales y empresarios a proteger su patrimonio, identificar oportunidades de crecimiento e inversión y tomar decisiones inmobiliarias con seguridad y confianza.',
    heroIntro3: 'Mi compromiso es ayudarte a construir un futuro más sólido a través de decisiones que generen valor, estabilidad y tranquilidad.',
    specialtyRealEstate: 'Bienes raíces',
    specialtyInsurance: 'Seguros',
    specialtyInvestments: 'Inversiones',
    whatsappButton: 'Ir a WhatsApp',
    purposeKicker: 'Propósito profesional',
    purposeTitle: 'Decisiones con estructura, calma y visión de futuro.',
    purposeText: 'Mi propósito es acompañarte a tomar decisiones que te den tranquilidad hoy y construyan tu futuro mañana.',
    servicesKicker: 'Áreas de asesoría',
    servicesTitle: 'Soluciones integrales para tu patrimonio',
    serviceRealEstateTitle: 'Bienes Raíces',
    serviceRealEstateText: 'Encuentra oportunidades inmobiliarias estratégicas que generen valor, estabilidad y crecimiento en el tiempo. Te asesoro en cada paso para que tomes decisiones seguras y rentables.',
    serviceInsuranceTitle: 'Seguros',
    serviceInsuranceText: 'Protege lo que has construido con soluciones diseñadas para resguardar tu patrimonio, tu familia y tu tranquilidad.',
    serviceInvestmentsTitle: 'Inversiones',
    serviceInvestmentsText: 'Diseñamos estrategias personalizadas para hacer crecer tu dinero con visión, control y propósito. Invertir bien no es suerte, es estructura.',
    impactKicker: 'Nicaragua · Visión estratégica',
    impactTitle: 'Una asesoría conectada con tus decisiones y con el territorio.',
    impactText: 'Cada decisión patrimonial merece contexto. Integro bienes raíces, seguros e inversiones para construir una estrategia clara, personalizada y preparada para crecer contigo.',
    stat1Value: '+5',
    stat1Label: 'Años de experiencia',
    stat2Value: '+220',
    stat2Label: 'Personas aseguradas',
    stat3Value: '+20',
    stat3Label: 'Propiedades vendidas',
    mapKicker: 'Cobertura estratégica',
    mapTitle: 'Nicaragua',
    mapLiveLabel: 'Presencia en movimiento',
    mapFooterText: 'Asesoría que trasciende una sola operación.',
  },
  realEstate: {
    searchHeroEyebrow: 'PORTAFOLIO INMOBILIARIO',
    searchHeroTitle: 'Encuentra tu próxima propiedad',
    searchHeroText: 'Explora oportunidades que encajen con lo que buscas.',
    catalogEyebrow: 'PROPIEDADES',
    catalogTitle: 'Propiedades disponibles',
    catalogText: 'Explora las oportunidades que Amy ha seleccionado para venta o alquiler.',
    featuredTitle: 'Propiedades destacadas',
    featuredText: 'Oportunidades que merecen una mirada especial.',
    heroEyebrow: 'SERVICIOS INMOBILIARIOS',
    heroTitle: 'Bienes raíces con estrategia, confianza y visión',
    heroText: 'Acompaño a compradores, vendedores e inversionistas en cada paso del proceso inmobiliario, brindando asesoría profesional, claridad en la toma de decisiones y oportunidades alineadas con sus objetivos.',
    heroPrimaryButton: 'Explorar propiedades',
    heroSecondaryButton: 'Agendar asesoría',
    heroBadgeTitle: 'Asesoría personalizada',
    heroBadgeText: 'Compra · Venta · Inversión',
    heroTrust1: 'Atención cercana',
    heroTrust2: 'Decisiones informadas',
    servicesKicker: 'SERVICIO INTEGRAL',
    servicesTitle: '¿Cómo puedo ayudarte?',
    servicesText: 'Soluciones inmobiliarias pensadas para acompañar tus objetivos con claridad y experiencia.',
    service1Title: 'Compra de propiedades',
    service1Text: 'Encuentra oportunidades alineadas con tu presupuesto, estilo de vida o visión de inversión.',
    service2Title: 'Venta de propiedades',
    service2Text: 'Te acompaño en la comercialización, presentación y captación de compradores potenciales.',
    service3Title: 'Inversión inmobiliaria',
    service3Text: 'Analizamos oportunidades con potencial de valorización, rentabilidad y seguridad patrimonial.',
    service4Title: 'Asesoría personalizada',
    service4Text: 'Recibe orientación estratégica y clara antes de tomar una decisión inmobiliaria importante.',
    processKicker: 'UNA RUTA CLARA',
    processTitle: 'Un acompañamiento inmobiliario más claro y estratégico',
    processText: 'Un proceso cercano, estructurado y enfocado en proteger tus intereses.',
    process1Title: 'Escucho tu objetivo',
    process1Text: 'Entendemos qué buscas y qué resultado quieres conseguir.',
    process2Title: 'Analizo oportunidades',
    process2Text: 'Evaluamos opciones con criterio, contexto y visión patrimonial.',
    process3Title: 'Te acompaño en la decisión',
    process3Text: 'Resolvemos dudas para que avances con claridad y confianza.',
    process4Title: 'Damos seguimiento',
    process4Text: 'Estoy presente durante la negociación y cada etapa del proceso.',
    ctaEyebrow: 'TU PRÓXIMO PASO',
    ctaTitle: '¿Buscas comprar, vender o invertir con respaldo profesional?',
    ctaText: 'Conversemos sobre tu próximo paso en bienes raíces.',
    ctaPrimaryButton: 'Contactar ahora',
    ctaSecondaryButton: 'Ver propiedades',
  },
  insurance: {
    heroEyebrow: 'PROTECCIÓN CON VISIÓN',
    heroTitle: 'Protege lo que has construido con decisiones más claras',
    heroText: 'Te acompaño a evaluar riesgos, entender coberturas y elegir soluciones de seguro que cuiden tu patrimonio, tu familia y tu tranquilidad.',
    heroPrimaryButton: 'Solicitar cotización',
    heroSecondaryButton: 'Conocer coberturas',
    heroTrust1: 'Asesoría personalizada',
    heroTrust2: 'Explicación clara',
    heroTrust3: 'Seguimiento cercano',
    heroShieldTitle: 'Respaldo profesional',
    heroShieldText: 'Protección para cada etapa',
    assurance1Title: 'Protección patrimonial',
    assurance1Text: 'Soluciones pensadas para cuidar lo que has construido.',
    assurance2Title: 'Decisiones informadas',
    assurance2Text: 'Compara y entiende antes de contratar.',
    assurance3Title: 'Acompañamiento humano',
    assurance3Text: 'Orientación cercana durante todo el proceso.',
    coveragesEyebrow: 'SOLUCIONES DE PROTECCIÓN',
    coveragesTitle: 'Coberturas para distintas áreas de tu vida',
    coveragesText: 'Analizamos cada necesidad de forma individual para construir una protección coherente, comprensible y útil. Toca una opción para conocerla en detalle.',
    guidanceEyebrow: 'ASESORÍA ANTES QUE VENTA',
    guidanceTitle: 'No se trata de contratar más. Se trata de estar mejor protegido.',
    guidanceText: 'Una póliza debe responder a una necesidad concreta. Por eso el proceso comienza entendiendo tu situación, tus riesgos y lo que realmente necesitas proteger.',
    guidancePoint1: 'Revisamos tus prioridades antes de recomendar una opción.',
    guidancePoint2: 'Explicamos exclusiones, alcances y condiciones relevantes.',
    guidancePoint3: 'Buscamos equilibrio entre protección, utilidad y presupuesto.',
    guidancePoint4: 'Puedes revisar tu estrategia cuando tus necesidades cambien.',
    guidanceButton: 'Evaluar mi protección',
    guidanceQuote: '“Una buena protección empieza con una decisión bien entendida.”',
    guidanceMetric1: 'Identificar lo que realmente quieres proteger.',
    guidanceMetric2: 'Conocer los riesgos que podrían afectar tu estabilidad.',
    guidanceMetric3: 'Elegir una cobertura alineada con tus prioridades.',
    processEyebrow: 'UN PROCESO SIMPLE',
    processTitle: 'De la necesidad a una protección bien estructurada',
    processText: 'Un acompañamiento ordenado para que avances con confianza, claridad y sin complicaciones innecesarias.',
    process1Title: 'Conocemos tu necesidad',
    process1Text: 'Conversamos sobre lo que quieres proteger, tus prioridades y el nivel de respaldo que necesitas.',
    process2Title: 'Revisamos alternativas',
    process2Text: 'Analizamos opciones y coberturas para que puedas entender diferencias, alcances y condiciones.',
    process3Title: 'Diseñamos una propuesta',
    process3Text: 'Organizamos una solución clara y proporcional a tu situación, evitando coberturas innecesarias.',
    process4Title: 'Te acompañamos',
    process4Text: 'Recibes orientación durante la contratación y seguimiento cuando necesites revisar o actualizar tu protección.',
    principlesEyebrow: 'MI FORMA DE ASESORAR',
    principlesTitle: 'Seguros con información, criterio y acompañamiento',
    principlesText: 'La confianza se construye cuando entiendes tus opciones y puedes elegir con seguridad.',
    principle1Title: 'Claridad antes de decidir',
    principle1Text: 'Te explico cada alternativa en un lenguaje sencillo para que sepas qué estás contratando y por qué.',
    principle2Title: 'Protección con propósito',
    principle2Text: 'La meta no es tener más pólizas, sino contar con coberturas que realmente respondan a tus riesgos.',
    principle3Title: 'Acompañamiento cercano',
    principle3Text: 'Cada recomendación parte de tu contexto, tus prioridades y la protección que necesitas construir.',
  },
  contact: {
    pageEyebrow: 'HABLEMOS',
    pageTitle: 'Contacto',
    pageText: 'Conversemos sobre la decisión que quieres tomar hoy para construir tu futuro mañana.',
    locationLabel: 'Ubicación',
    contactNote: 'Atención personalizada para bienes raíces, seguros e inversiones.',
    formEyebrow: 'CUÉNTAME SOBRE TU SOLICITUD',
    formTitle: '¿Cómo puedo ayudarte?',
    formText: 'Completa tus datos y recibirás seguimiento lo antes posible.',
    phone: '+505 8832 4439',
    whatsapp: '+505 8832 4439',
    email: 'info@amyblandon.com',
    address: 'Matagalpa, Nicaragua',
    schedule: 'Lunes a viernes',
    facebook: '',
    instagram: '',
    tiktok: '',
    realEstateEmail: '',
    realEstateFacebook: '',
    realEstateInstagram: '',
    realEstateTiktok: '',
    insuranceEmail: '',
    insuranceFacebook: '',
    insuranceInstagram: '',
    insuranceTiktok: '',
  },
  footer: {
    question: 'Cual será tu próxima inversion?',
    whatsappButton: 'Ir a WhatsApp',
    subscribeTitle: 'Suscribete',
    subscribeText: 'Sé parte de nuestra comunidad y recibe información valiosa sobre bienes raíces, seguros e inversiones. Aprende, mantente informado y toma mejores decisiones financieras.',
    subscribePlaceholder: 'Correo electrónico',
    submitLabel: 'Enviar',
    successMessage: 'Gracias por suscribirte.',
    errorMessage: 'Ingresa un correo electrónico válido.',
    copyright: 'Copyright © 2026 - Amy Blandón.com | Powered by Xarcon',
  },
};

export async function getSiteContent(section) {
  const defaults = defaultSiteContent[section] || {};
  if (!firebaseEnabled) return defaults;
  const snap = await getDoc(doc(db, 'siteContent', section));
  return { ...defaults, ...(snap.exists() ? snap.data() : {}) };
}

export async function saveSiteContent(section, data) {
  if (!firebaseEnabled) return data;
  return setDoc(doc(db, 'siteContent', section), { ...data, updatedAt: serverTimestamp() }, { merge: true });
}
