export const aboutContentDefaults = {
  heroKicker: 'SOBRE MÍ',
  heroTitle: 'Estrategia, experiencia y visión para proteger tu patrimonio.',
  heroName: 'Amy Blandón',
  heroRole: 'Asesora Inmobiliaria | Seguros | Inversiones',
  heroText: 'Creo que las mejores decisiones patrimoniales no se toman por impulso, sino con información, estrategia y una visión clara de futuro.',
  heroCta: 'Conóceme y descubre mi forma de trabajar',

  purposeKicker: 'MI PROPÓSITO',
  purposeTitle: 'Ayudarte a tomar decisiones que te den tranquilidad hoy y construyan tu futuro mañana.',
  purposeText: 'Mi propósito es acompañarte a tomar decisiones patrimoniales con claridad, estrategia y confianza.\n\nIntegro bienes raíces, seguros e inversiones para ayudarte a construir una estructura financiera más sólida, proteger lo que has construido y aprovechar nuevas oportunidades de crecimiento.',
  purposeWord1: 'Construir',
  purposeWord2: 'Proteger',
  purposeWord3: 'Crecer',

  workKicker: 'MI FORMA DE TRABAJAR',
  workTitle: 'Cada decisión comienza con una buena conversación.',
  work1Title: 'ESCUCHAR',
  work1Lead: 'Entender antes de recomendar.',
  work1Text: 'Conocer tus objetivos, necesidades, prioridades y contexto.',
  work2Title: 'ESTRUCTURAR',
  work2Lead: 'Convertir tus objetivos en estrategia.',
  work2Text: 'Analizar opciones y construir una ruta clara, ordenada y realista.',
  work3Title: 'ACOMPAÑAR',
  work3Lead: 'Estar presente en cada decisión.',
  work3Text: 'No se trata solo de encontrar una propiedad, contratar un seguro o invertir. Se trata de acompañarte en el proceso.',

  areasKicker: 'ÁREAS DE ASESORÍA',
  areasTitle: 'Una visión integral de tu patrimonio',
  area1Verb: 'CONSTRUIR',
  area1Title: 'Bienes Raíces',
  area1Text: 'Encuentra oportunidades inmobiliarias que puedan convertirse en patrimonio, hogar o inversión.',
  area2Verb: 'PROTEGER',
  area2Title: 'Seguros',
  area2Text: 'Protege tu patrimonio, tu familia y aquello que has construido frente a los riesgos que pueden cambiar tus planes.',
  area3Verb: 'CRECER',
  area3Title: 'Inversiones',
  area3Text: 'Diseña estrategias para hacer crecer tu capital con visión, estructura y propósito.',

  philosophyKicker: 'MI FILOSOFÍA',
  philosophyTitle: 'No se trata solo de encontrar una oportunidad. Se trata de saber qué hacer con ella.',
  philosophyText: 'Una buena decisión patrimonial necesita contexto.\n\nPor eso creo en escuchar primero, analizar después y recomendar con responsabilidad.\n\nMi objetivo es que cada decisión que tomes tenga sentido para tu presente y contribuya al futuro que quieres construir.',
};

export const aboutEditorSection = {
  label: 'Sobre mí',
  route: '/sobre-mi',
  description: 'Narrativa de marca personal de Amy: presentación, propósito, forma de trabajar, áreas de asesoría y filosofía.',
  groups: [
    {
      title: 'Portada / Presentación',
      description: 'Textos que acompañan la fotografía principal de Amy.',
      fields: [
        ['heroKicker', 'Etiqueta superior', 'text'],
        ['heroTitle', 'Título principal', 'textarea', 3],
        ['heroName', 'Nombre', 'text'],
        ['heroRole', 'Cargo / especialidades', 'text'],
        ['heroText', 'Texto de presentación', 'textarea', 5],
        ['heroCta', 'Texto del enlace “Conóceme”', 'text'],
      ],
    },
    {
      title: 'Mi propósito',
      description: 'Bloque azul marino y frase final Construir · Proteger · Crecer.',
      fields: [
        ['purposeKicker', 'Etiqueta superior', 'text'],
        ['purposeTitle', 'Título', 'textarea', 3],
        ['purposeText', 'Texto', 'textarea', 7],
        ['purposeWord1', 'Palabra 1', 'text'],
        ['purposeWord2', 'Palabra 2', 'text'],
        ['purposeWord3', 'Palabra 3', 'text'],
      ],
    },
    {
      title: 'Mi forma de trabajar',
      fields: [
        ['workKicker', 'Etiqueta superior', 'text'],
        ['workTitle', 'Título', 'textarea', 2],
        ['work1Title', 'Paso 01 — Título', 'text'],
        ['work1Lead', 'Paso 01 — Frase destacada', 'textarea', 2],
        ['work1Text', 'Paso 01 — Descripción', 'textarea', 3],
        ['work2Title', 'Paso 02 — Título', 'text'],
        ['work2Lead', 'Paso 02 — Frase destacada', 'textarea', 2],
        ['work2Text', 'Paso 02 — Descripción', 'textarea', 3],
        ['work3Title', 'Paso 03 — Título', 'text'],
        ['work3Lead', 'Paso 03 — Frase destacada', 'textarea', 2],
        ['work3Text', 'Paso 03 — Descripción', 'textarea', 4],
      ],
    },
    {
      title: 'Tres áreas, una sola visión',
      fields: [
        ['areasKicker', 'Etiqueta superior', 'text'],
        ['areasTitle', 'Título', 'textarea', 2],
        ['area1Verb', 'Área 1 — Concepto', 'text'],
        ['area1Title', 'Área 1 — Título', 'text'],
        ['area1Text', 'Área 1 — Descripción', 'textarea', 4],
        ['area2Verb', 'Área 2 — Concepto', 'text'],
        ['area2Title', 'Área 2 — Título', 'text'],
        ['area2Text', 'Área 2 — Descripción', 'textarea', 4],
        ['area3Verb', 'Área 3 — Concepto', 'text'],
        ['area3Title', 'Área 3 — Título', 'text'],
        ['area3Text', 'Área 3 — Descripción', 'textarea', 4],
      ],
    },
    {
      title: 'Mi filosofía',
      description: 'Texto que aparece junto a la fotografía natural de Amy.',
      fields: [
        ['philosophyKicker', 'Etiqueta superior', 'text'],
        ['philosophyTitle', 'Título', 'textarea', 3],
        ['philosophyText', 'Texto', 'textarea', 8],
      ],
    },
  ],
};
