import {
  BriefcaseBusiness,
  Car,
  HeartPulse,
  Home,
  Umbrella,
  UsersRound,
} from 'lucide-react';

export const insuranceCoverages = [
  {
    slug: 'vida-salud',
    icon: HeartPulse,
    index: '01',
    title: 'Vida y salud',
    shortText: 'Protección pensada para cuidar tu estabilidad y la de quienes dependen de ti ante situaciones inesperadas.',
    note: 'Bienestar · Respaldo familiar',
    eyebrow: 'PROTECCIÓN PERSONAL Y FAMILIAR',
    heroTitle: 'Protección para cuidar tu bienestar y la estabilidad de quienes más importan',
    heroText: 'Una estrategia de vida y salud ayuda a prepararte ante eventos que pueden afectar tus ingresos, tu patrimonio o la tranquilidad de tu familia. La asesoría parte de tus prioridades para revisar alternativas de protección comprensibles y sostenibles.',
    overviewTitle: 'Una cobertura pensada para proteger mucho más que el presente',
    overviewText: 'Los seguros de vida y salud pueden formar parte de una estrategia de previsión para enfrentar gastos médicos, proteger a las personas que dependen de ti y reducir el impacto financiero de situaciones inesperadas. Cada alternativa debe evaluarse según edad, necesidades, presupuesto y condiciones de contratación.',
    pillars: [
      ['Respaldo familiar', 'Ayuda a construir una red de protección económica para las personas que dependen de ti.'],
      ['Atención y bienestar', 'Permite evaluar alternativas orientadas a respaldar gastos o servicios relacionados con la salud.'],
      ['Planificación financiera', 'Integra la protección dentro de una visión de estabilidad y continuidad patrimonial.'],
    ],
    benefits: [
      'Mayor preparación financiera frente a eventos inesperados.',
      'Opciones adaptables a distintas etapas personales y familiares.',
      'Posibilidad de complementar la protección existente según tus necesidades.',
      'Orientación para comprender beneficios, límites, exclusiones y condiciones.',
      'Evaluación del nivel de protección de acuerdo con tus responsabilidades económicas.',
      'Acompañamiento para comparar alternativas antes de tomar una decisión.',
    ],
    idealFor: [
      'Personas con familiares o dependientes económicos.',
      'Profesionales que desean fortalecer su planificación financiera.',
      'Familias que buscan anticiparse a gastos médicos o contingencias.',
      'Personas interesadas en revisar si su protección actual sigue siendo suficiente.',
    ],
    questions: [
      ['¿Qué quiero proteger?', 'Tu salud, tus ingresos, la estabilidad de tu familia o una combinación de estas prioridades.'],
      ['¿Por cuánto tiempo?', 'La necesidad de protección puede cambiar con tus responsabilidades, edad y etapa de vida.'],
      ['¿Qué nivel de respaldo necesito?', 'La recomendación debe guardar relación con tus compromisos económicos y presupuesto.'],
    ],
  },
  {
    slug: 'hogar-patrimonio',
    icon: Home,
    index: '02',
    title: 'Hogar y patrimonio',
    shortText: 'Coberturas orientadas a proteger tu vivienda, bienes y patrimonio frente a riesgos que pueden afectar tu tranquilidad.',
    note: 'Vivienda · Bienes',
    eyebrow: 'PROTECCIÓN DE VIVIENDA Y BIENES',
    heroTitle: 'Tu hogar representa años de esfuerzo. Protégelo con una estrategia adecuada.',
    heroText: 'Una vivienda concentra patrimonio, recuerdos y bienes de valor. Revisar una cobertura adecuada permite prepararse frente a determinados daños o eventos que podrían generar un impacto económico importante.',
    overviewTitle: 'Protección patrimonial diseñada alrededor de tu vivienda',
    overviewText: 'No todas las propiedades ni todos los hogares tienen los mismos riesgos. La asesoría permite revisar características del inmueble, bienes que deseas proteger y necesidades específicas para identificar alternativas de cobertura coherentes con tu realidad.',
    pillars: [
      ['Vivienda', 'Evaluación de alternativas para proteger la estructura del inmueble frente a riesgos contemplados por la póliza.'],
      ['Bienes personales', 'Posibilidad de considerar mobiliario, equipos u otros bienes según el producto contratado.'],
      ['Responsabilidad', 'Revisión de coberturas que pueden ayudar frente a determinadas responsabilidades relacionadas con el inmueble.'],
    ],
    benefits: [
      'Reduce la exposición financiera frente a determinados daños importantes.',
      'Permite analizar la protección de vivienda y bienes dentro de una misma estrategia.',
      'Puede adaptarse al tipo, uso y características del inmueble.',
      'Facilita comprender deducibles, límites, exclusiones y condiciones.',
      'Ayuda a revisar si el valor asegurado guarda relación con el patrimonio protegido.',
      'Acompañamiento profesional para elegir coberturas relevantes y evitar decisiones por impulso.',
    ],
    idealFor: [
      'Propietarios de casas, apartamentos u otras viviendas.',
      'Familias que han invertido significativamente en mobiliario o equipamiento.',
      'Personas que desean proteger un inmueble como parte de su patrimonio.',
      'Propietarios que quieren revisar o actualizar una cobertura existente.',
    ],
    questions: [
      ['¿Qué valor estoy protegiendo?', 'Es importante diferenciar el inmueble, su contenido y los bienes que deseas considerar.'],
      ['¿Cuáles son mis principales riesgos?', 'La ubicación, uso y características del inmueble influyen en las necesidades de protección.'],
      ['¿Mi cobertura está actualizada?', 'El valor del patrimonio y las necesidades pueden cambiar con el tiempo.'],
    ],
  },
  {
    slug: 'vehiculos',
    icon: Car,
    index: '03',
    title: 'Vehículos',
    shortText: 'Alternativas para proteger tu vehículo y contar con respaldo ante accidentes, daños o responsabilidades frente a terceros.',
    note: 'Auto · Responsabilidad',
    eyebrow: 'PROTECCIÓN PARA TU MOVILIDAD',
    heroTitle: 'Conduce con la tranquilidad de contar con una protección mejor entendida',
    heroText: 'Tu vehículo forma parte de tu patrimonio y de tu movilidad diaria. Una cobertura adecuada debe considerar el uso que le das, el valor del vehículo y los riesgos frente a los que deseas contar con respaldo.',
    overviewTitle: 'Una decisión que protege tu vehículo y tu estabilidad financiera',
    overviewText: 'Los seguros para vehículos pueden contemplar distintos niveles de protección. La clave está en entender qué cubre cada alternativa, cuáles son sus límites y qué responsabilidades necesitas considerar antes de contratar.',
    pillars: [
      ['Daños al vehículo', 'Revisión de alternativas que contemplen determinados daños según las condiciones de la póliza.'],
      ['Responsabilidad frente a terceros', 'Protección orientada a determinadas responsabilidades derivadas de un evento cubierto.'],
      ['Asistencia', 'Evaluación de servicios o asistencias adicionales que pueden acompañar algunas pólizas.'],
    ],
    benefits: [
      'Ayuda a reducir el impacto económico de determinados accidentes o daños.',
      'Permite seleccionar un nivel de protección acorde al valor y uso del vehículo.',
      'Facilita entender deducibles y condiciones antes de necesitar utilizar la póliza.',
      'Puede incorporar alternativas de asistencia según el producto disponible.',
      'Brinda mayor claridad sobre responsabilidades frente a terceros.',
      'Acompañamiento para revisar opciones sin contratar coberturas innecesarias.',
    ],
    idealFor: [
      'Propietarios de vehículos de uso personal o familiar.',
      'Personas que utilizan su vehículo con alta frecuencia.',
      'Quienes desean proteger una inversión importante en movilidad.',
      'Conductores que quieren revisar si su póliza actual responde a sus necesidades.',
    ],
    questions: [
      ['¿Cómo utilizo mi vehículo?', 'La frecuencia y tipo de uso ayudan a definir qué riesgos son más relevantes.'],
      ['¿Qué nivel de protección busco?', 'No todas las personas necesitan la misma combinación de coberturas.'],
      ['¿Entiendo mi deducible?', 'Conocerlo antes de contratar ayuda a tomar una decisión financiera más consciente.'],
    ],
  },
  {
    slug: 'negocios',
    icon: BriefcaseBusiness,
    index: '04',
    title: 'Negocios',
    shortText: 'Soluciones para empresas, oficinas y actividades comerciales que necesitan continuidad y protección frente a riesgos operativos.',
    note: 'Empresa · Continuidad',
    eyebrow: 'PROTECCIÓN PARA EMPRESAS',
    heroTitle: 'Protege la continuidad de tu negocio y el patrimonio que lo hace posible',
    heroText: 'Una empresa enfrenta riesgos distintos a los de una persona o una vivienda. Analizar esos riesgos permite estructurar una protección más coherente para instalaciones, activos, operación y responsabilidades del negocio.',
    overviewTitle: 'La continuidad también se planifica',
    overviewText: 'Una estrategia de seguros para negocios comienza identificando qué activos y procesos son críticos. A partir de ahí se revisan alternativas disponibles para proteger aquello que podría comprometer la operación o generar una pérdida financiera relevante.',
    pillars: [
      ['Activos del negocio', 'Evaluación de instalaciones, equipos, inventario u otros activos que resulten relevantes.'],
      ['Continuidad operativa', 'Análisis de riesgos que podrían interrumpir o afectar el funcionamiento de la empresa.'],
      ['Responsabilidades', 'Revisión de determinadas responsabilidades propias de la actividad comercial según la cobertura disponible.'],
    ],
    benefits: [
      'Ayuda a identificar riesgos que pueden comprometer la operación.',
      'Permite priorizar los activos esenciales para la continuidad del negocio.',
      'Facilita estructurar una protección proporcional al tamaño y actividad de la empresa.',
      'Aporta claridad sobre límites, exclusiones y requisitos de las coberturas evaluadas.',
      'Puede integrarse a una estrategia más amplia de gestión de riesgos.',
      'Acompañamiento para revisar la protección a medida que el negocio crece o cambia.',
    ],
    idealFor: [
      'Emprendedores y propietarios de pequeños y medianos negocios.',
      'Oficinas, comercios y empresas con activos físicos importantes.',
      'Negocios que dependen de equipos, inventario o instalaciones para operar.',
      'Empresas que desean ordenar su estrategia de protección y continuidad.',
    ],
    questions: [
      ['¿Qué no puede detenerse?', 'Identificar los procesos críticos ayuda a priorizar la estrategia de protección.'],
      ['¿Qué activos son esenciales?', 'Equipos, instalaciones e inventario pueden tener diferentes niveles de exposición.'],
      ['¿Cómo ha cambiado mi empresa?', 'El crecimiento puede hacer que una cobertura antigua ya no responda a la realidad actual.'],
    ],
  },
  {
    slug: 'familia',
    icon: UsersRound,
    index: '05',
    title: 'Familia',
    shortText: 'Opciones de protección diseñadas para acompañar las distintas etapas de tu familia y ayudarte a planificar con mayor seguridad.',
    note: 'Familia · Previsión',
    eyebrow: 'PREVISIÓN PARA CADA ETAPA',
    heroTitle: 'Una estrategia de protección que evoluciona junto con tu familia',
    heroText: 'Las responsabilidades cambian con el tiempo: hijos, vivienda, educación, salud y proyectos futuros. Revisar la protección familiar permite construir una estrategia que acompañe esas etapas con mayor claridad.',
    overviewTitle: 'Proteger a tu familia también significa planificar con anticipación',
    overviewText: 'No existe una única solución para todas las familias. La asesoría analiza prioridades, dependientes, compromisos económicos y objetivos para identificar alternativas que ayuden a fortalecer la estabilidad familiar.',
    pillars: [
      ['Previsión', 'Organización de necesidades actuales y futuras para priorizar aquello que requiere mayor protección.'],
      ['Estabilidad', 'Evaluación de alternativas que ayuden a reducir el impacto financiero de determinados imprevistos.'],
      ['Evolución', 'La estrategia puede revisarse cuando cambian tus responsabilidades, patrimonio o etapa familiar.'],
    ],
    benefits: [
      'Ayuda a ordenar las prioridades de protección de todo el núcleo familiar.',
      'Permite identificar brechas entre responsabilidades y protección disponible.',
      'Facilita revisar diferentes soluciones bajo una misma visión de previsión.',
      'Puede adaptarse conforme cambian los integrantes y necesidades de la familia.',
      'Promueve decisiones informadas en lugar de contrataciones aisladas.',
      'Acompañamiento para entender opciones, condiciones y alcance de cada alternativa.',
    ],
    idealFor: [
      'Familias con hijos o personas económicamente dependientes.',
      'Parejas que están construyendo patrimonio y proyectos a largo plazo.',
      'Personas que desean ordenar distintas necesidades de protección familiar.',
      'Familias que atraviesan cambios importantes en sus responsabilidades.',
    ],
    questions: [
      ['¿Quién depende de mí?', 'Las responsabilidades económicas son una referencia importante para definir prioridades.'],
      ['¿Qué proyectos quiero proteger?', 'Vivienda, educación y estabilidad futura pueden formar parte de la planificación.'],
      ['¿Cuándo revisé mi estrategia?', 'Una protección adecuada debe evolucionar cuando cambia tu realidad familiar.'],
    ],
  },
  {
    slug: 'proteccion-integral',
    icon: Umbrella,
    index: '06',
    title: 'Protección integral',
    shortText: 'Evaluamos tus prioridades para construir una combinación de coberturas coherente con tu realidad, patrimonio y objetivos.',
    note: 'Asesoría · Estrategia',
    eyebrow: 'ESTRATEGIA DE PROTECCIÓN INTEGRAL',
    heroTitle: 'Conecta tus necesidades de protección dentro de una estrategia más completa',
    heroText: 'Cuando existen varias responsabilidades —familia, vivienda, vehículo, negocio o patrimonio— conviene dejar de ver cada seguro de forma aislada. Una revisión integral permite ordenar prioridades y detectar posibles brechas de protección.',
    overviewTitle: 'Una visión completa para tomar decisiones con mayor criterio',
    overviewText: 'La protección integral no significa contratar todo. Significa revisar tu situación de manera global, identificar riesgos relevantes y decidir qué soluciones tienen sentido para ti, evitando duplicidades y coberturas que no aporten valor.',
    pillars: [
      ['Diagnóstico', 'Revisión general de prioridades, responsabilidades, patrimonio y coberturas existentes.'],
      ['Coherencia', 'Organización de soluciones para que cada cobertura responda a una necesidad concreta.'],
      ['Seguimiento', 'Actualización de la estrategia cuando cambian tus proyectos, patrimonio o responsabilidades.'],
    ],
    benefits: [
      'Permite visualizar tu protección como un conjunto y no como pólizas aisladas.',
      'Ayuda a identificar áreas importantes que podrían estar desprotegidas.',
      'Puede detectar duplicidades o coberturas que merecen una revisión.',
      'Facilita priorizar según nivel de riesgo, objetivos y presupuesto.',
      'Crea una base más ordenada para futuras decisiones de protección.',
      'Acompañamiento periódico para adaptar la estrategia a cambios importantes.',
    ],
    idealFor: [
      'Personas con diferentes activos y responsabilidades que desean ordenar su protección.',
      'Familias con vivienda, vehículos y compromisos financieros diversos.',
      'Emprendedores que combinan patrimonio personal y actividad empresarial.',
      'Quienes ya cuentan con varias pólizas y quieren revisar si siguen teniendo sentido.',
    ],
    questions: [
      ['¿Dónde están mis principales riesgos?', 'La estrategia comienza identificando qué eventos tendrían mayor impacto en tu estabilidad.'],
      ['¿Tengo brechas o duplicidades?', 'Revisar las coberturas en conjunto ayuda a detectar áreas que merecen atención.'],
      ['¿Qué debo priorizar?', 'El nivel de impacto, la probabilidad y tu presupuesto ayudan a ordenar las decisiones.'],
    ],
  },
];

export const insuranceCoverageBySlug = Object.fromEntries(
  insuranceCoverages.map((coverage) => [coverage.slug, coverage]),
);
