export const nicaraguaDepartments = [
  'Boaco',
  'Carazo',
  'Chinandega',
  'Chontales',
  'Costa Caribe Norte',
  'Costa Caribe Sur',
  'Estelí',
  'Granada',
  'Jinotega',
  'León',
  'Madriz',
  'Managua',
  'Masaya',
  'Matagalpa',
  'Nueva Segovia',
  'Río San Juan',
  'Rivas',
];

export const areaUnitOptions = [
  ['m²', 'Metros cuadrados (m²)'],
  ['varas²', 'Varas cuadradas (vrs²)'],
  ['manzanas', 'Manzanas'],
  ['hectáreas', 'Hectáreas'],
  ['pies²', 'Pies cuadrados (ft²)'],
];

export const rentPeriodOptions = [
  ['monthly', 'Mensual'],
  ['daily', 'Diario'],
  ['weekly', 'Semanal'],
  ['yearly', 'Anual'],
];

export const highlightTagOptions = [
  ['new', 'Nueva'],
  ['featured', 'Destacada'],
  ['opportunity', 'Oportunidad'],
  ['reduced', 'Precio reducido'],
  ['exclusive', 'Exclusiva'],
  ['investment', 'Ideal para inversión'],
];

export const featurePresets = [
  'Piscina',
  'Terraza',
  'Jardín',
  'Balcón',
  'Área social',
  'Vista panorámica',
  'Aire acondicionado',
  'Amueblada',
  'Cuarto de servicio',
  'Área de lavandería',
  'Bodega',
  'Cerca perimetral',
  'Seguridad 24/7',
  'Acceso controlado',
  'Ascensor',
  'Planta eléctrica',
];

export const servicePresets = [
  'Agua potable',
  'Energía eléctrica',
  'Internet',
  'Alcantarillado sanitario',
  'Drenaje pluvial',
  'Recolección de basura',
  'Calle pavimentada',
  'Calle adoquinada',
  'Acceso todo el año',
  'Transporte público cercano',
  'Pozo propio',
  'Energía trifásica',
];

const yesNo = [
  ['yes', 'Sí'],
  ['no', 'No'],
];

const field = (key, label, type = 'text', options = [], help = '') => ({
  key,
  label,
  type,
  options,
  help,
});

export const dynamicPropertyFields = {
  house: [
    field('levels', 'Niveles', 'number'),
    field('livingRoom', 'Sala', 'select', yesNo),
    field('diningRoom', 'Comedor', 'select', yesNo),
    field('kitchen', 'Cocina', 'select', yesNo),
    field('patio', 'Patio', 'select', yesNo),
    field('terrace', 'Terraza', 'select', yesNo),
    field('laundryArea', 'Área de lavandería', 'select', yesNo),
    field('furnished', 'Amueblada', 'select', yesNo),
    field('constructionStatus', 'Estado de la construcción'),
    field('security', 'Sistema de seguridad'),
  ],
  apartment: [
    field('floorLevel', 'Piso o nivel'),
    field('elevator', 'Ascensor', 'select', yesNo),
    field('balcony', 'Balcón', 'select', yesNo),
    field('furnished', 'Amueblado', 'select', yesNo),
    field('maintenanceFee', 'Cuota de mantenimiento', 'number'),
    field('condoAmenities', 'Amenidades del condominio', 'textarea'),
    field('security', 'Seguridad'),
  ],
  condo: [
    field('floorLevel', 'Piso o nivel'),
    field('elevator', 'Ascensor', 'select', yesNo),
    field('balcony', 'Balcón', 'select', yesNo),
    field('furnished', 'Amueblado', 'select', yesNo),
    field('maintenanceFee', 'Cuota de condominio', 'number'),
    field('condoAmenities', 'Amenidades del condominio', 'textarea'),
    field('security', 'Seguridad'),
  ],
  villa: [
    field('levels', 'Niveles', 'number'),
    field('pool', 'Piscina', 'select', yesNo),
    field('gardens', 'Jardines', 'select', yesNo),
    field('socialArea', 'Área social', 'select', yesNo),
    field('furnished', 'Amueblada', 'select', yesNo),
    field('viewType', 'Tipo de vista'),
    field('security', 'Seguridad'),
  ],
  quinta: [
    field('pool', 'Piscina', 'select', yesNo),
    field('gardens', 'Jardines', 'select', yesNo),
    field('socialArea', 'Área social', 'select', yesNo),
    field('mainHouse', 'Casa principal', 'select', yesNo),
    field('caretakerHouse', 'Casa de cuidador', 'select', yesNo),
    field('well', 'Pozo', 'select', yesNo),
    field('vehicleAccess', 'Acceso vehicular'),
    field('naturalEnvironment', 'Entorno natural'),
    field('potentialUse', 'Uso potencial', 'textarea'),
  ],
  land: [
    field('landType', 'Categoría del terreno', 'select', [
      ['urban', 'Urbano'],
      ['semiurban', 'Semiurbano'],
      ['semirural', 'Semirrural'],
      ['rural', 'Rural'],
    ]),
    field('topography', 'Topografía', 'select', [
      ['flat', 'Plana'],
      ['semiflat', 'Semiplana'],
      ['sloped', 'Inclinada'],
      ['mixed', 'Mixta'],
      ['irregular', 'Irregular'],
    ]),
    field('landShape', 'Forma del terreno', 'select', [
      ['regular', 'Regular'],
      ['irregular', 'Irregular'],
      ['rectangular', 'Rectangular'],
      ['corner', 'Esquinero'],
    ]),
    field('soilType', 'Tipo de suelo'),
    field('streetType', 'Tipo de calle'),
    field('accessType', 'Tipo de acceso'),
    field('potentialUse', 'Uso potencial', 'textarea'),
    field('documentation', 'Documentación disponible', 'textarea'),
  ],
  lot: [
    field('landType', 'Categoría del solar', 'select', [
      ['urban', 'Urbano'],
      ['semiurban', 'Semiurbano'],
      ['semirural', 'Semirrural'],
      ['rural', 'Rural'],
    ]),
    field('topography', 'Topografía'),
    field('landShape', 'Forma del solar'),
    field('soilType', 'Tipo de suelo'),
    field('streetType', 'Tipo de calle'),
    field('accessType', 'Acceso'),
    field('potentialUse', 'Uso potencial', 'textarea'),
  ],
  farm: [
    field('currentUse', 'Uso actual', 'select', [
      ['cattle', 'Ganadería'],
      ['agriculture', 'Agricultura'],
      ['coffee', 'Café'],
      ['forestry', 'Forestal'],
      ['mixed', 'Mixto'],
      ['investment', 'Inversión'],
    ]),
    field('topography', 'Topografía'),
    field('accessType', 'Tipo de acceso'),
    field('streetType', 'Tipo de calle'),
    field('well', 'Pozo', 'select', yesNo),
    field('waterSource', 'Río, quebrada o fuente de agua'),
    field('fences', 'Cercas', 'select', yesNo),
    field('paddocks', 'Potreros'),
    field('crops', 'Cultivos'),
    field('existingInfrastructure', 'Infraestructura existente', 'textarea'),
    field('documentation', 'Documentación', 'textarea'),
    field('potentialUse', 'Potencial de la finca', 'textarea'),
  ],
  commercial: [
    field('commercialFront', 'Frente comercial'),
    field('trafficLevel', 'Nivel de tráfico'),
    field('streetType', 'Tipo de calle'),
    field('commercialZone', 'Zona comercial'),
    field('internalWarehouse', 'Bodega interna', 'select', yesNo),
    field('permittedUse', 'Uso permitido'),
    field('idealFor', 'Ideal para', 'textarea'),
    field('security', 'Seguridad'),
  ],
  warehouse: [
    field('height', 'Altura libre'),
    field('truckAccess', 'Acceso para camiones', 'select', yesNo),
    field('internalOffices', 'Oficinas internas', 'select', yesNo),
    field('threePhasePower', 'Energía trifásica', 'select', yesNo),
    field('loadingArea', 'Área de carga y descarga', 'select', yesNo),
    field('industrialZone', 'Zona industrial o comercial'),
    field('constructionStatus', 'Estado de la construcción'),
    field('security', 'Seguridad'),
  ],
  office: [
    field('privateRooms', 'Ambientes privados', 'number'),
    field('meetingRoom', 'Sala de reuniones', 'select', yesNo),
    field('reception', 'Recepción', 'select', yesNo),
    field('elevator', 'Ascensor', 'select', yesNo),
    field('furnished', 'Amueblada', 'select', yesNo),
    field('connectivity', 'Internet y conectividad'),
    field('corporateLocation', 'Entorno corporativo'),
  ],
  building: [
    field('levels', 'Cantidad de niveles', 'number'),
    field('units', 'Cantidad de unidades', 'number'),
    field('elevator', 'Ascensor', 'select', yesNo),
    field('commercialSpaces', 'Locales comerciales', 'number'),
    field('occupancyStatus', 'Estado de ocupación'),
    field('currentIncome', 'Ingreso mensual actual', 'number'),
    field('potentialUse', 'Uso potencial', 'textarea'),
  ],
  hotel: [
    field('rooms', 'Cantidad de habitaciones', 'number'),
    field('occupancyStatus', 'Estado de operación'),
    field('restaurant', 'Restaurante', 'select', yesNo),
    field('pool', 'Piscina', 'select', yesNo),
    field('conferenceRoom', 'Salón de eventos', 'select', yesNo),
    field('parkingCapacity', 'Capacidad de estacionamiento', 'number'),
    field('furnished', 'Equipado y amueblado', 'select', yesNo),
    field('investmentDetails', 'Información para inversionistas', 'textarea'),
  ],
  investment: [
    field('projectType', 'Tipo de proyecto'),
    field('potentialUse', 'Uso potencial'),
    field('existingPermits', 'Permisos existentes'),
    field('availableStudies', 'Estudios disponibles'),
    field('capitalGainProjection', 'Proyección de plusvalía'),
    field('mainRoadsProximity', 'Cercanía a vías principales'),
    field('documentation', 'Documentación', 'textarea'),
    field('investorIdeal', 'Perfil de inversionista ideal', 'textarea'),
  ],
  beach_house: [
    field('beachDistance', 'Distancia al mar'),
    field('oceanView', 'Vista al mar', 'select', yesNo),
    field('pool', 'Piscina', 'select', yesNo),
    field('furnished', 'Amueblada', 'select', yesNo),
    field('rentalPotential', 'Potencial de alquiler vacacional', 'textarea'),
    field('accessType', 'Tipo de acceso'),
  ],
  other: [
    field('specificFeatures', 'Características específicas', 'textarea'),
  ],
};

export const propertySections = [
  ['basic', 'Información principal'],
  ['commercial', 'Precio y publicación'],
  ['location', 'Ubicación y mapa'],
  ['details', 'Medidas y características'],
  ['media', 'Fotografías y multimedia'],
  ['marketing', 'Presentación y posicionamiento'],
];

export const getDynamicFields = (propertyType) =>
  dynamicPropertyFields[propertyType] || dynamicPropertyFields.other;
