import { defaultBrandLogo } from '../content/defaultBrandLogo';

export const siteImages = {
  favicon: '',
  brandLogo: defaultBrandLogo,
  // Fondo anterior conservado únicamente como respaldo técnico del hero.
  heroBackground: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1800&q=85',
  // Set premium predeterminado del Hero de Inicio. Cada slot puede reemplazarse desde el panel privado.
  heroHome1: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2200&q=90',
  heroHome2: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=2200&q=90',
  heroHome3: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=2200&q=90',
  heroHome4: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=2200&q=90',
  // Hero de Sobre mí: un fondo fijo separado y hasta cuatro imágenes recortadas de Amy que rotan automáticamente.
  aboutHeroBackground: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=2200&q=90',
  aboutHeroAmy1: '',
  aboutHeroAmy2: '',
  aboutHeroAmy3: '',
  aboutHeroAmy4: '',
  // No se usa una persona predeterminada: Firebase debe proporcionar la imagen real del hero.
  heroPerson: '',
  aboutHome: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1000&q=85',
  aboutPage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1000&q=85',
  aboutPhilosophy: '',
  aboutEditorialHero: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=2000&q=90',
  signature: '',
  strategicBanner: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1800&q=85',
  realEstateHero: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=85',
  heroBr1: 'https://images.unsplash.com/photo-1691521335568-31b92876e124?auto=format&fit=crop&w=2600&q=90',
  heroBr2: 'https://images.unsplash.com/photo-1648876672455-56cc2aa32b65?auto=format&fit=crop&w=2600&q=90',
  heroBr3: 'https://images.unsplash.com/photo-1561810746-95ab82a3348b?auto=format&fit=crop&w=2600&q=90',
  heroBr4: 'https://images.unsplash.com/photo-1584904558330-f9772a6778c5?auto=format&fit=crop&w=2600&q=90',
  heroBr5: 'https://images.unsplash.com/photo-1642521713828-7e0b40bb3545?auto=format&fit=crop&w=2600&q=90',
  insuranceHero: '',
  propertyOne: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1000&q=80',
  propertyTwo: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
  propertyThree: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
};

// Alias temporales para componentes antiguos que todavía puedan usar estas claves.
siteImages.hero = siteImages.heroPerson;
siteImages.aboutAmy = siteImages.aboutHome;

export const siteImageSlots = [
  {
    key: 'favicon',
    label: 'Favicon del sitio',
    shortLabel: 'Icono de la pestaña',
    description: 'Icono que aparece en la pestaña del navegador, favoritos y accesos directos. Se carga desde Firebase Storage y se aplica automáticamente en la web pública.',
    recommendation: 'PNG o WEBP cuadrado. Recomendado: 512 × 512 px, con el símbolo centrado y poco margen alrededor para que se distinga bien en tamaños pequeños.',
    preview: 'transparent',
  },
  {
    key: 'brandLogo',
    label: 'Logo principal',
    shortLabel: 'Nombre AMY BLANDON',
    description: 'Imagen utilizada únicamente para el nombre gráfico “AMY BLANDON” del navbar. El subtítulo se genera como texto desde la web y cambia de color según el fondo del navbar.',
    recommendation: 'Sube solo “AMY BLANDON”, sin el texto inferior. PNG o WEBP con fondo transparente y formato horizontal. Recomendado: 1400 × 280 px, con el nombre ocupando casi todo el lienzo y poco margen transparente.',
    preview: 'transparent',
  },
  {
    key: 'heroHome1',
    label: 'Hero de Inicio — Imagen 1',
    shortLabel: 'Slide 01 · Bienes Raíces',
    description: 'Primera imagen del carrusel del Inicio. El fondo predeterminado muestra una residencia moderna de alto nivel y comunica bienes raíces premium.',
    recommendation: 'JPG o WEBP de alta resolución. Recomendado: 1800 × 2200 px o superior. Mantén el punto de interés cerca del centro para que funcione bien en PC y móvil.',
    preview: 'background',
    group: 'heroHome',
  },
  {
    key: 'heroHome2',
    label: 'Hero de Inicio — Imagen 2',
    shortLabel: 'Slide 02 · Seguros',
    description: 'Segunda imagen del carrusel del Inicio. El fondo predeterminado representa asesoría profesional, planificación y confianza.',
    recommendation: 'JPG o WEBP de alta resolución. Recomendado: 1800 × 2200 px o superior. Evita textos incrustados y composiciones demasiado cargadas.',
    preview: 'background',
    group: 'heroHome',
  },
  {
    key: 'heroHome3',
    label: 'Hero de Inicio — Imagen 3',
    shortLabel: 'Slide 03 · Inversiones',
    description: 'Tercera imagen del carrusel del Inicio. El fondo predeterminado utiliza arquitectura corporativa para comunicar inversión, crecimiento y patrimonio.',
    recommendation: 'JPG o WEBP de alta resolución. Recomendado: 1800 × 2200 px o superior. Prioriza arquitectura, ciudad o finanzas con una estética sobria y luxury.',
    preview: 'background',
    group: 'heroHome',
  },
  {
    key: 'heroHome4',
    label: 'Hero de Inicio — Imagen 4',
    shortLabel: 'Slide 04 · Patrimonio',
    description: 'Cuarta imagen del carrusel del Inicio. Cierra el ciclo con una escena residencial interior de alta gama vinculada a patrimonio y estilo de vida.',
    recommendation: 'JPG o WEBP de alta resolución. Recomendado: 1800 × 2200 px o superior. Busca una escena elegante, limpia y con buena lectura detrás de la silueta de Amy.',
    preview: 'background',
    group: 'heroHome',
  },
  {
    key: 'aboutHeroBackground',
    label: 'Hero Sobre mí — Fondo',
    shortLabel: 'Fondo fijo del hero',
    description: 'Imagen de fondo independiente del Hero de Sobre mí. Permanece fija mientras las imágenes recortadas de Amy se desplazan automáticamente encima.',
    recommendation: 'JPG o WEBP horizontal de alta resolución. Recomendado: 1800 × 1200 px o superior. Evita personas y deja una composición limpia para colocar a Amy encima.',
    preview: 'background',
    group: 'heroAbout',
  },
  {
    key: 'aboutHeroAmy1',
    label: 'Hero Sobre mí — Amy 1',
    shortLabel: 'Amy · Slide 01',
    description: 'Primera imagen de Amy del carrusel del Hero de Sobre mí.',
    recommendation: 'PNG o WEBP con fondo transparente. Recomendado: 1100 × 1500 px o superior, incluyendo el cuerpo/asiento que quieras mostrar.',
    preview: 'transparent',
    group: 'heroAbout',
  },
  {
    key: 'aboutHeroAmy2',
    label: 'Hero Sobre mí — Amy 2',
    shortLabel: 'Amy · Slide 02',
    description: 'Segunda imagen de Amy. Aparece después del primer retrato manteniendo el mismo fondo fijo.',
    recommendation: 'PNG o WEBP con fondo transparente. Usa un encuadre y escala parecidos al Slide 01 para que la transición sea uniforme.',
    preview: 'transparent',
    group: 'heroAbout',
  },
  {
    key: 'aboutHeroAmy3',
    label: 'Hero Sobre mí — Amy 3',
    shortLabel: 'Amy · Slide 03',
    description: 'Tercera imagen opcional de Amy para ampliar la rotación automática del hero.',
    recommendation: 'PNG o WEBP con fondo transparente. Recomendado: 1100 × 1500 px o superior.',
    preview: 'transparent',
    group: 'heroAbout',
  },
  {
    key: 'aboutHeroAmy4',
    label: 'Hero Sobre mí — Amy 4',
    shortLabel: 'Amy · Slide 04',
    description: 'Cuarta imagen opcional de Amy. Cierra el ciclo antes de volver automáticamente al Slide 01.',
    recommendation: 'PNG o WEBP con fondo transparente. Recomendado: 1100 × 1500 px o superior.',
    preview: 'transparent',
    group: 'heroAbout',
  },
  {
    key: 'realEstateHero',
    label: 'Hero Bienes Raíces',
    shortLabel: 'Hero inmobiliario',
    description: 'Fotografía principal de Amy para la portada de la sección de Bienes Raíces.',
    recommendation: 'JPG, PNG o WEBP vertical. Recomendado: 1200 × 1500 px o superior.',
    preview: 'portrait',
  },
  {
    key: 'heroBr1',
    label: 'Imagen Hero BR 1',
    shortLabel: 'Slide 01',
    description: 'Primera imagen del carrusel animado que aparece detrás del buscador de Bienes Raíces.',
    recommendation: 'JPG o WEBP horizontal. Recomendado: 2200 × 1300 px o superior. Usa fotografías amplias, premium y con el punto de interés cerca del centro.',
    preview: 'background',
    group: 'heroBr',
  },
  {
    key: 'heroBr2',
    label: 'Imagen Hero BR 2',
    shortLabel: 'Slide 02',
    description: 'Segunda imagen del carrusel animado que aparece detrás del buscador de Bienes Raíces.',
    recommendation: 'JPG o WEBP horizontal. Recomendado: 2200 × 1300 px o superior. Evita encuadres demasiado cerrados porque el hero aplica un zoom suave.',
    preview: 'background',
    group: 'heroBr',
  },
  {
    key: 'heroBr3',
    label: 'Imagen Hero BR 3',
    shortLabel: 'Slide 03',
    description: 'Tercera imagen del carrusel animado que aparece detrás del buscador de Bienes Raíces.',
    recommendation: 'JPG o WEBP horizontal. Recomendado: 2200 × 1300 px o superior. Prioriza propiedades, ciudades o paisajes con composición limpia.',
    preview: 'background',
    group: 'heroBr',
  },
  {
    key: 'heroBr4',
    label: 'Imagen Hero BR 4',
    shortLabel: 'Slide 04',
    description: 'Cuarta imagen del carrusel animado que aparece detrás del buscador de Bienes Raíces.',
    recommendation: 'JPG o WEBP horizontal. Recomendado: 2200 × 1300 px o superior. Mantén buena resolución para pantallas grandes.',
    preview: 'background',
    group: 'heroBr',
  },
  {
    key: 'heroBr5',
    label: 'Imagen Hero BR 5',
    shortLabel: 'Slide 05',
    description: 'Quinta imagen del carrusel animado que aparece detrás del buscador de Bienes Raíces.',
    recommendation: 'JPG o WEBP horizontal. Recomendado: 2200 × 1300 px o superior. Esta imagen cierra el ciclo antes de volver al slide 01.',
    preview: 'background',
    group: 'heroBr',
  },
  {
    key: 'insuranceHero',
    label: 'Hero Seguros',
    shortLabel: 'Hero de seguros',
    description: 'Fotografía principal utilizada en la portada de la página de Seguros. Si no se carga una imagen específica, la web utiliza temporalmente la fotografía de la página Sobre mí.',
    recommendation: 'JPG, PNG o WEBP vertical. Recomendado: 1200 × 1500 px o superior, con espacio alrededor del rostro para permitir el recorte responsive.',
    preview: 'portrait',
  },
  {
    key: 'heroBackground',
    label: 'Fondo anterior del Hero de Inicio',
    shortLabel: 'Respaldo del hero',
    description: 'Imagen histórica conservada únicamente como respaldo técnico si los cuatro slides del Hero de Inicio no estuvieran disponibles.',
    recommendation: 'No es necesario modificar este espacio. Gestiona el hero desde la categoría “Hero de Inicio”.',
    preview: 'background',
    group: 'legacy',
  },
  {
    key: 'heroPerson',
    label: 'Portada Hero — Persona',
    shortLabel: 'Persona del hero',
    description: 'Imagen independiente de Amy que se superpone sobre los cuatro fondos rotativos del Hero de Inicio.',
    recommendation: 'PNG o WEBP con fondo transparente. Recomendado: 1000 × 1400 px o superior.',
    preview: 'transparent',
  },
  {
    key: 'aboutHome',
    label: 'Imagen Sobre mí — Inicio',
    shortLabel: 'Sobre mí en inicio',
    description: 'Fotografía utilizada en la sección “Sobre mí” de la página de inicio.',
    recommendation: 'JPG, PNG o WEBP vertical. Recomendado: 1000 × 1300 px.',
    preview: 'portrait',
  },
  {
    key: 'signature',
    label: 'Firma de Amy',
    shortLabel: 'Firma',
    description: 'Firma gráfica que aparece al final del bloque “Sobre mí” de la página de inicio y queda disponible para reutilizarla en otras secciones de la web.',
    recommendation: 'PNG o WEBP con fondo transparente. Recomendado: 1000 × 320 px, firma centrada y con poco margen transparente alrededor.',
    preview: 'transparent',
  },
  {
    key: 'aboutPage',
    label: 'Imagen Sobre mí — Página interna',
    shortLabel: 'Sobre mí interna',
    description: 'Fotografía principal de la nueva portada de la página completa “Sobre mí”. Se conserva como respaldo mientras no se configuren las imágenes del nuevo Hero Sobre mí.',
    recommendation: 'JPG, PNG o WEBP vertical. Recomendado: 1000 × 1300 px o superior.',
    preview: 'portrait',
  },
  {
    key: 'aboutEditorialHero',
    label: 'Portada editorial — Sobre mí',
    shortLabel: 'Portada editorial',
    description: 'Imagen panorámica del hero editorial de “Sobre mí”. Debe comunicar una estética inmobiliaria luxury, patrimonio y visión de inversión.',
    recommendation: 'JPG o WEBP horizontal. Recomendado: 1800 × 900 px o superior, con una propiedad premium y composición limpia para recorte responsive.',
    preview: 'background',
  },
  {
    key: 'aboutPhilosophy',
    label: 'Imagen Sobre mí — Mi filosofía',
    shortLabel: 'Foto de filosofía',
    description: 'Segunda fotografía, más natural, utilizada junto al bloque “Mi filosofía”. Ideal para la fotografía de Amy con la tablet.',
    recommendation: 'JPG, PNG o WEBP vertical. Recomendado: 1000 × 1300 px o superior. Si no se carga, se reutiliza temporalmente la imagen “Sobre mí — Inicio”.',
    preview: 'portrait',
  },
  {
    key: 'strategicBanner',
    label: 'Fondo del banner estratégico',
    shortLabel: 'Banner estratégico',
    description: 'Imagen panorámica situada detrás del mensaje estratégico de la página de inicio.',
    recommendation: 'JPG o WEBP horizontal. Recomendado: 1920 × 900 px o superior.',
    preview: 'background',
  },
];

export const siteImageSlotKeys = new Set(siteImageSlots.map(({ key }) => key));
